# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('album_title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.FileField(max_length=500, upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('audio', models.FileField(max_length=500, upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('video', models.FileField(max_length=500, upload_to='')),
                ('album', models.ForeignKey(default='Mugen', on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
