# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_favorite',
        ),
    ]
