# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
