# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20171208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
