# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
