# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio',
            new_name='track',
        ),
    ]
