# Generated by Django 2.0.3 on 2018-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20171208_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_logo',
            field=models.FileField(default='img', max_length=500, upload_to=''),
        ),
    ]
